language: android
jdk: openjdk8

android:
  components:
    - tools #latest for "builtin" sdk
    - tools #latest
    - platform-tools #latest
    - build-tools-26.0.2
    - android-26
    - extra-android-m2repository

before_install:
- export ANDROID_HOME=/usr/local/android-sdk
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- echo "sdk.dir=$ANDROID_HOME" > local.properties

script:
  - ./gradlew clean
  - ./gradlew testReleaseUnitTestCoverage
